#!/usr/bin/env python3
#
# Experiment with defining Unicode shorthand for Python.
# Mostly, you can do it if the Unicode you want is identifier chars, but not operators.
#
IOTA = ι = enumerate
#NOT = ¬ = not
#AND = ⋀ = and
#OR = ⋁ = or
#MOD =  = mod

#INFINITY = Inf = ∞ = math.inf
#Nan = = math.nan

#SUM = ∑ = ∑ = list.sum
#PRODUCT = ∏ = math.prod
#LAMBDA = λ = lambda

#FORALL = ∀ = for
#EXISTS = ∃ =
#NECESSARILY =  =
#POSSIBLY =  =
#EMPTY = ∅ = set([])
#DELTA = ∆ =

GAMMA = γ = math.gamma
PI = π = math.pi
TAU = τ = math.tau
EPSILON = ε = math.e
EULER = ℇ = 0.5772156649015328606065120900824024310421
PLANK = ℎ = 6.62607004E-34
PHI = φ = math.phi

#CROSSPRODUCT = ⨯ =
#DOTPRODUCT = ⋅ =
#UNION = ∪ = set.union
#INTERSECTION = ∩ = set.intersection
#MEMBER = ∈ = __in__
#CONTAINS = ∋ = __contains__
#NOTCONTAINS = ∌ = lambda x, y: not(__contains__(x,y))
#SUBSET = ⊆ = set.issubset
#SUPERSET = ⊇ = set.issuperset
#PSUBSET = ⊃ =
#PSUPERSET = ⊃ =

# "NOT" versions

#ISCLOSE = ≅ = math.isclose
NOTCLOSE = ≇ = lambda x, y: not math.isclose(x,y)
IS = ≡ = is
#ISNOT = ≢ =

|x|, ceil, floor
reversed?
push/pop/shift/append/insert
location(s) of

"""
U+02336  ⌶  APL FUNCTIONAL SYMBOL I-BEAM
U+02337  ⌷  APL FUNCTIONAL SYMBOL SQUISH QUAD
U+02338  ⌸  APL FUNCTIONAL SYMBOL QUAD EQUAL
U+02339  ⌹  APL FUNCTIONAL SYMBOL QUAD DIVIDE
U+0233a  ⌺  APL FUNCTIONAL SYMBOL QUAD DIAMOND
U+0233b  ⌻  APL FUNCTIONAL SYMBOL QUAD JOT
U+0233c  ⌼  APL FUNCTIONAL SYMBOL QUAD CIRCLE
U+0233d  ⌽  APL FUNCTIONAL SYMBOL CIRCLE STILE
U+0233e  ⌾  APL FUNCTIONAL SYMBOL CIRCLE JOT
U+0233f  ⌿  APL FUNCTIONAL SYMBOL SLASH BAR
U+02340  ⍀  APL FUNCTIONAL SYMBOL BACKSLASH BAR
U+02341  ⍁  APL FUNCTIONAL SYMBOL QUAD SLASH
U+02342  ⍂  APL FUNCTIONAL SYMBOL QUAD BACKSLASH
U+02343  ⍃  APL FUNCTIONAL SYMBOL QUAD LESS-THAN
U+02344  ⍄  APL FUNCTIONAL SYMBOL QUAD GREATER-THAN
U+02345  ⍅  APL FUNCTIONAL SYMBOL LEFTWARDS VANE
U+02346  ⍆  APL FUNCTIONAL SYMBOL RIGHTWARDS VANE
U+02347  ⍇  APL FUNCTIONAL SYMBOL QUAD LEFTWARDS ARROW
U+02348  ⍈  APL FUNCTIONAL SYMBOL QUAD RIGHTWARDS ARROW
U+02349  ⍉  APL FUNCTIONAL SYMBOL CIRCLE BACKSLASH
U+0234a  ⍊  APL FUNCTIONAL SYMBOL DOWN TACK UNDERBAR
U+0234b  ⍋  APL FUNCTIONAL SYMBOL DELTA STILE
U+0234c  ⍌  APL FUNCTIONAL SYMBOL QUAD DOWN CARET
U+0234d  ⍍  APL FUNCTIONAL SYMBOL QUAD DELTA
U+0234e  ⍎  APL FUNCTIONAL SYMBOL DOWN TACK JOT
U+0234f  ⍏  APL FUNCTIONAL SYMBOL UPWARDS VANE
U+02350  ⍐  APL FUNCTIONAL SYMBOL QUAD UPWARDS ARROW
U+02351  ⍑  APL FUNCTIONAL SYMBOL UP TACK OVERBAR
U+02352  ⍒  APL FUNCTIONAL SYMBOL DEL STILE
U+02353  ⍓  APL FUNCTIONAL SYMBOL QUAD UP CARET
U+02354  ⍔  APL FUNCTIONAL SYMBOL QUAD DEL
U+02355  ⍕  APL FUNCTIONAL SYMBOL UP TACK JOT
U+02356  ⍖  APL FUNCTIONAL SYMBOL DOWNWARDS VANE
U+02357  ⍗  APL FUNCTIONAL SYMBOL QUAD DOWNWARDS ARROW
U+02358  ⍘  APL FUNCTIONAL SYMBOL QUOTE UNDERBAR
U+02359  ⍙  APL FUNCTIONAL SYMBOL DELTA UNDERBAR
U+0235a  ⍚  APL FUNCTIONAL SYMBOL DIAMOND UNDERBAR
U+0235b  ⍛  APL FUNCTIONAL SYMBOL JOT UNDERBAR
U+0235c  ⍜  APL FUNCTIONAL SYMBOL CIRCLE UNDERBAR
U+0235d  ⍝  APL FUNCTIONAL SYMBOL UP SHOE JOT
U+0235e  ⍞  APL FUNCTIONAL SYMBOL QUOTE QUAD
U+0235f  ⍟  APL FUNCTIONAL SYMBOL CIRCLE STAR
U+02360  ⍠  APL FUNCTIONAL SYMBOL QUAD COLON
U+02361  ⍡  APL FUNCTIONAL SYMBOL UP TACK DIAERESIS
U+02362  ⍢  APL FUNCTIONAL SYMBOL DEL DIAERESIS
U+02363  ⍣  APL FUNCTIONAL SYMBOL STAR DIAERESIS
U+02364  ⍤  APL FUNCTIONAL SYMBOL JOT DIAERESIS
U+02365  ⍥  APL FUNCTIONAL SYMBOL CIRCLE DIAERESIS
U+02366  ⍦  APL FUNCTIONAL SYMBOL DOWN SHOE STILE
U+02367  ⍧  APL FUNCTIONAL SYMBOL LEFT SHOE STILE
U+02368  ⍨  APL FUNCTIONAL SYMBOL TILDE DIAERESIS
U+02369  ⍩  APL FUNCTIONAL SYMBOL GREATER-THAN DIAERESIS
U+0236a  ⍪  APL FUNCTIONAL SYMBOL COMMA BAR
U+0236b  ⍫  APL FUNCTIONAL SYMBOL DEL TILDE
U+0236c  ⍬  APL FUNCTIONAL SYMBOL ZILDE
U+0236d  ⍭  APL FUNCTIONAL SYMBOL STILE TILDE
U+0236e  ⍮  APL FUNCTIONAL SYMBOL SEMICOLON UNDERBAR
U+0236f  ⍯  APL FUNCTIONAL SYMBOL QUAD NOT EQUAL
U+02370  ⍰  APL FUNCTIONAL SYMBOL QUAD QUESTION
U+02371  ⍱  APL FUNCTIONAL SYMBOL DOWN CARET TILDE
U+02372  ⍲  APL FUNCTIONAL SYMBOL UP CARET TILDE
U+02373  ⍳  APL FUNCTIONAL SYMBOL IOTA
U+02374  ⍴  APL FUNCTIONAL SYMBOL RHO
U+02375  ⍵  APL FUNCTIONAL SYMBOL OMEGA
U+02376  ⍶  APL FUNCTIONAL SYMBOL ALPHA UNDERBAR
U+02377  ⍷  APL FUNCTIONAL SYMBOL EPSILON UNDERBAR
U+02378  ⍸  APL FUNCTIONAL SYMBOL IOTA UNDERBAR
U+02379  ⍹  APL FUNCTIONAL SYMBOL OMEGA UNDERBAR
U+0237a  ⍺  APL FUNCTIONAL SYMBOL ALPHA
U+02395  ⎕  APL FUNCTIONAL SYMBOL QUAD
"""
